Working better
payfunc/selectively pull request #31
Opened 2021-02-24 18:07 UTC by robinnedergard

2021-02-25 08:20 UTC, florianebmeier requested changes

2021-02-25 08:20 UTC, florianebmeier commented on CompareHelper.ts
> +			? Object.entries(input).reduce<number | string | undefined>((r, c) => {
remove unnecessary braces and return `  (r,c) => r ? r : ........ : undefined `

2021-02-25 08:35 UTC, florianebmeier submitted a review, later dismissed

2021-02-25 08:53 UTC, nilssonemma submitted a review, later dismissed

2021-02-26 14:03 UTC, fredrikbryntesson approved these changes

2021-02-26 14:03 UTC, merged