Fixed comparator operations.
payfunc/selectively pull request #49
Opened 2021-03-24 16:38 UTC by marcushanses

2021-03-24 16:45 UTC, florianebmeier approved these changes

2021-03-25 08:43 UTC, robinnedergard requested changes

2021-03-25 08:43 UTC, robinnedergard commented on GreaterThan.ts
> +	toString(): string {
Not correct, fix toString() for comparisons and add tests.

2021-03-25 09:31 UTC, robinnedergard approved these changes

2021-03-25 09:42 UTC, fredrikbryntesson approved these changes

2021-03-25 09:42 UTC, merged