Modified and copied the parser into Expression.ts.
payfunc/selectively pull request #66
Opened 2021-04-12 14:25 UTC by marcushanses

Added parsers for Value and InfixOperator.

2021-04-12 15:44 UTC, robinnedergard requested changes

2021-04-12 15:44 UTC, robinnedergard commented on parse/Expression.ts
> +			break
While statement should be able to do this

2021-04-12 15:44 UTC, robinnedergard commented on parse/Expression.ts
> +	(source: Source, previous: Expression | number | undefined) => Expression | undefined | false,
Why false?

2021-04-13 07:15 UTC, robinnedergard requested changes

2021-04-13 07:15 UTC, robinnedergard commented on parse/Expression.ts
> +	while (+!result ^ +algebra) {
`!result != algebra`

(or `!result != !!algebra` but algebra is already a boolean)

2021-04-13 11:56 UTC, robinnedergard requested changes

2021-04-13 11:56 UTC, robinnedergard commented on parse/Value.ts
> +	let result: Expression | undefined | false
let result: Expression | undefined

2021-04-13 13:29 UTC, robinnedergard approved these changes

2021-04-13 20:11 UTC, fredrikbryntesson approved these changes

2021-04-13 20:11 UTC, merged