Boolean literals and general improvements.
payfunc/selectively pull request #93
Opened 2021-05-13 14:56 UTC by marcushanses

2021-05-17 12:14 UTC, robinnedergard requested changes

2021-05-17 12:14 UTC, robinnedergard commented on Type/String.ts
> +
whitespace added for no reason

2021-05-18 12:48 UTC, florianebmeier approved these changes

2021-05-18 15:30 UTC, robinnedergard approved these changes

2021-05-18 20:24 UTC, fredrikbryntesson approved these changes

2021-05-18 20:25 UTC, merged